version: '{build}'
os: Visual Studio 2015

configuration: Release

environment:
  NSIS_ROOT: $(APPVEYOR_BUILD_FOLDER)\Shared\Installer\NSIS

before_build:
  - utils\premake5 vs2015
  - genversion

after_build:
  - utils\premake5 compose_files
  - cinst nsis --version 3.0 -y -installArgs /D=%NSIS_ROOT%
  - cd %NSIS_ROOT%
  - makensis ..\sao.nsi
  - cd ..
  - ren SAO*Setup.exe SAO-Setup.exe
  
clone_depth: 1
  
build:
  parallel: true
  project: Build/SAO.sln
  #verbosity: minimal

artifacts:
  - path: Shared/Installer/SAO-Setup.exe
    name: SAO
