version: '{build}'
image: Visual Studio 2015

configuration: Release

platform:
  - Win32
  #- x64

environment:
  NSIS_ROOT: $(APPVEYOR_BUILD_FOLDER)\Shared\Installer\NSIS

before_build:
  - utils\premake5 vs2015
  - genversion

after_build:
  - utils\premake5 compose_files
  - cinst nsis --version 3.0 -y -installArgs /D=%NSIS_ROOT%
  - cd %NSIS_ROOT%
  - makensis ..\sao.nsi
  - cd ..
  - ren SAO*Setup.exe SAO-Setup.exe
  - move SAO-Setup.exe ..\..\

skip_tags: true
clone_depth: 1
  
build:
  parallel: true
  project: Build/SAO.sln
  #verbosity: minimal

deploy: off
artifacts:
  - path: SAO-Setup.exe
    name: SAO
