version: '{build}'
os: Visual Studio 2015

configuration: Release

environment:
  NSIS_ROOT: $(APPVEYOR_BUILD_FOLDER)\Shared\Installer\NSIS

before_build:
  - utils\premake5 vs2015

after_build:
  - utils\premake5 compose_files
  - cd InstallFiles
  - for /f %%a in ('powershell -Command "Get-Date -format yyyyMMdd-HHmm"') do set datetime=%%a
  - 7z a ..\SAO.zip .
  # TODO: Build installer with NSIS' command line utilities
  # install NSIS 3.0
  - cinst nsis --version 3.0 -y -installArgs /D=%NSIS_ROOT%
  - cd %NSIS_ROOT%
  - makensis.exe Shared\Installer\sao.nsi
  
clone_depth: 1
  
build:
  parallel: true
  project: Build/SAO.sln
  #verbosity: minimal

artifacts:
  - path: SAO.zip
    name: SAO
