# AppVeyor build configuration
# Author(s):       iFarbod <ifarbod@outlook.com>
#
# Copyright (c) 2015-2017 Project CtNorth
#
# Distributed under the MIT license (See accompanying file LICENSE or copy at
# https://opensource.org/licenses/MIT)


#---------------------------------#
#      general configuration      #
#---------------------------------#
version: '{build}'

branches:
  only:
    - master

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017 RC

clone_depth: 1

environment:
  NSIS_ROOT: $(APPVEYOR_BUILD_FOLDER)\Shared\Installer\NSIS

#---------------------------------#
#       build configuration       #
#---------------------------------#
platform:
  - Win32
  #- x64

configuration: Release

before_build:
  - genversion
  - utils\premake5 install_cef
  - utils\premake5 vs2017

build:
  parallel: true
  project: Build/CtNorth.sln
  verbosity: minimal

after_build:
  - utils\premake5 install_data
  - utils\premake5 compose_files
  - cinst nsis --version 3.0 -y -installArgs /D=%NSIS_ROOT%
  - cd %NSIS_ROOT%
  - makensis ..\sao.nsi
  - cd ..
  - ren SAO*Setup.exe SAO-Setup.exe
  - move SAO-Setup.exe ..\..\

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: SAO-Setup.exe
    name: SAO

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  # GitHub PR comment
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  # Webhook
  - provider: Webhook
    url:
      secure: hJnDftoFJ8Y3VMd1+WbIatNw/0g0obj2zoTpUl7/wD38kCoXPZnDImGUij6nsNjB
    method: POST
    headers:
      User-Agent:
        secure: mHZnOSogybs+z9aEU2ayo9n2+1nqLdUnu+HxgHaQP9/PoyfzxfbFJdjzha509tv/lHIrk9LaFfidBuRD4t9vePV8BvRCeMlxfdy19+Un9E//Qp79W4SQxHHsStUAjK3D2/GrCZJX9zn/kn4rYPfC2Qlk6aYWLz+KaS6F6xxelQ4=
    content_type: application/json
    body: "{'text':'test'}"
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
